name: Provision t2.micro EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest
  
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
      - name: Checkout repository
        uses: actions/checkout@v4

    # Install the latest version of Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.TF_USER_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_USER_AWS_SECRET }}
          aws-region: us-east-1

    # Decode SSH private key and set permissions
      - name: Decode SSH private key
        run: echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/private-key.pem

      - name: Set permissions for SSH private key
        run: chmod 600 /tmp/private-key.pem

    # Initialize a new or existing Terraform working directory
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

    # Generate an execution plan for Terraform
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false

    # Apply the generated plan
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_ssh_private_key_path: /tmp/private-key.pem

    # Save EC2 Public IP
      - name: Save EC2 Public IP
        id: save-ec2-ip
        run: echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
